config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "flats#index"
  resources :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    def index
        @flats = Flat.all
    end

    def show
        @flat = Flat.find(params[:id])
    end

    def new
        @flat = Flat.new
    end

    def create
        @flat = Flat.new(flat_params)
        @flat.save
        redirect_to flat_path(@flat)
    end

    def edit
        @flat = Flat.find(params[:id])
    end

    def update
        @flat = Flat.find(params[:id])
        @flat.update(flat_params)
        redirect_to flat_path(@flat)
    end

    def destroy
        @flat = Flat.find(params[:id])
        @flat.destroy
        redirect_to root_path, status: :see_other
    end

    private
        def flat_params
            params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1> Edit flat </h1>

<%= form_with model:@flat do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :address %>
        <%= f.text_field :address %>
    </div>

    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <div>
        <%= f.label :price_per_night %>
        <%= f.number_field :price_per_night %>
    </div>

    <div>
        <%= f.label :number_of_guests %>
        <%= f.number_field :number_of_guests %>
    </div>

    <div>
    <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<h1>Flats</h1>

<%= link_to "New Flat", new_flat_path %>
<ul>
  <% @flats.each do |flat| %>
    <li>
    <%= link_to flat.name, flat_path(flat) %>
    </li>
  <% end %>
</ul>

app/views/flats/new.html.erb

<h1> New flat </h1>

<%= form_with model:@flat do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :address %>
        <%= f.text_field :address %>
    </div>

    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <div>
        <%= f.label :price_per_night %>
        <%= f.number_field :price_per_night %>
    </div>

    <div>
        <%= f.label :number_of_guests %>
        <%= f.number_field :number_of_guests %>
    </div>

    <div>
    <%= f.submit %>
    </div>
<% end %>


app/views/flats/show.html.erb
<h1> Flat details </h1>
<p> Name: <%= @flat.name %> </p>
<p> Address: <%= @flat.address %> </p>
<p> Description: <%= @flat.description %> </p>
<p> Price per night: <%= @flat.price_per_night %> </p>
<p> Number of guests: <%= @flat.number_of_guests %> </p>


<li><%= link_to "Destroy", flat_path(@flat), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>